version: '3'
services:
  worker:
    build: .
    environment:
      LISTEN_ADDR: ":80"
      SCENELIB_ADDR: "http://scenelib:80"
    command: "grayt.worker"
  api:
    build: .
    ports:
      - "8081:80"
    environment:
      LISTEN_ADDR: ":80"
      SCENELIB_ADDR: "scenelib:80"
      WORKER_ADDR: "worker:80"
      ASSETS_DIR: "assets"
    command: "grayt.api"
  old:
    build: .
    ports:
      - "8080:8080"
    command: "grayt"
