version: '3'
services:
  new:
    build: .
    ports:
      - "8082:80"
    environment:
      LISTEN_ADDR: ":80"
      ASSETS_DIR: "assets"
    command: "grayt"
  api:
    build: .
    ports:
      - "8081:80"
    environment:
      LISTEN_ADDR: ":80"
      ASSETS_DIR: "assets"
    command: "grayt.api"
  old:
    build: .
    ports:
      - "8080:8080"
    command: "grayt.old"
